services:
  redis-streams:
    container_name: redis
    image: redis
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - ./src/ingress-redis-streams/data:/data
      - ./src/ingress-redis-streams/redis.conf:/usr/local/etc/redis/redis.conf
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    depends_on:
      - flyway # Not necessary, but we want the flyway to start first

  worker:
    build:
      context: ./src/worker
      dockerfile: Dockerfile
    depends_on:
      - redis-streams
      - database
      - flyway
    deploy:
      replicas: ${WORKER_COUNT} # Retrieved automtaically from .env file
      resources:
        reservations:
          cpus: '1'
          memory: 256M

  database:
    container_name: database-server-dab-p2-cad31c90-8310-42b6-97cd-efa824f683ba
    image: postgres:14.1
    restart: "no"
    env_file:
      - src/project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./src/flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - src/project.env

  manager:
    build:
      context: ./src/manager
      dockerfile: Dockerfile
    image: manager
    restart: "no"
    volumes:
      - ./src/manager/:/app
    depends_on:
      - flyway
      - redis-streams
      - simulator
    environment:
      - WORKER_COUNT=${WORKER_COUNT}

  simulator:
    build:
      context: ./src/simulator
      dockerfile: Dockerfile
    depends_on:
      - redis-streams
      - flyway  # Not necessary, but we want the flyway to start first
    volumes:
      - ./data/:/data