[package]
name = "worker"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "worker"
path = "src/main.rs"

[dependencies]
chrono = "0.4.38"
postgres = { version = "0.19.9", features = ["with-chrono-0_4"]}
redis = "0.27.5"
