{
 "title": "my-dashboard",
 "time": { "from": "2024-11-07T23:39:59.947Z", "to": "2024-11-20T19:24:45.328Z" },
 "templating": {
  "list": [
   { "name": "stock_id", "label": "Stock Name", "query": "SELECT symbol FROM symbols" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# CS-E4780 Scalable Systems and Data Management Project Dashboard"
   }
  },
  {
   "title": "Invalid events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) \r\nfrom alerts \r\nwhere created_at between $__timeFrom() and $__timeTo() "
    }
   ]
  },
  {
   "title": "Valid events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n  COUNT(message_count)\r\nfrom indicators \r\nwhere created_at between $__timeFrom() and $__timeTo() "
    }
   ]
  },
  {
   "title": "Bullish stocks",
   "type": "logs",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 2 },
   "targets": [
    {
     "rawSql": "select \r\n  symbol, \r\n  created_at as time, \r\n  ema_38 as \"EMA 38\", \r\n  ema_100 as \"EMA 100\", \r\n  last_trade_timestamp as \"Most recent trade\", \r\n  message_count as \"Events in last window\", \r\n  average_latency_ms as \"Average latency (ms)\" \r\nfrom indicators \r\nwhere \r\n  bullish=true \r\n  AND created_at > NOW() - INTERVAL '10 seconds' \r\nORDER BY symbol;"
    }
   ]
  },
  {
   "title": "Bearish stocks",
   "type": "logs",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 2 },
   "targets": [
    {
     "rawSql": "select \r\n  symbol, \r\n  created_at as time, \r\n  ema_38 as \"EMA 38\", \r\n  ema_100 as \"EMA 100\", \r\n  last_trade_timestamp as \"Most recent trade\", \r\n  message_count as \"Events in last window\", \r\n  average_latency_ms as \"Average latency (ms)\" \r\nfrom indicators \r\nwhere \r\n  bearish=true \r\n  AND created_at > NOW() - INTERVAL '10 seconds'\r\nORDER BY symbol;"
    }
   ]
  },
  {
   "title": "Stock events in last window",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  message_count\r\nFROM \r\n  indicators\r\nWHERE\r\n  symbol = '555200.ETR' AND\r\n  created_at > NOW() - INTERVAL '10 seconds' \r\nLIMIT \r\n  1;"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  AVG(latency_ms) / 1000 AS latency\r\nFROM (\r\n  SELECT average_latency_ms AS latency_ms\r\n  FROM indicators\r\n  WHERE \r\n    created_at > NOW() - INTERVAL '10 seconds'\r\n    AND message_count > 0\r\n  LIMIT 100\r\n) AS limited_data;"
    }
   ]
  },
  {
   "title": "EMA development",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT ema_100 as \"EMA 100\", created_at as time FROM indicators WHERE symbol = '$stock_id';"
    },
    {
     "rawSql": "SELECT ema_38 as \"EMA 38\", created_at as time FROM indicators WHERE symbol = '$stock_id';"
    }
   ]
  },
  {
   "title": "Most recent price",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  last_price as \"Last price\", \r\n  created_at as time \r\nFROM \r\n  indicators \r\nWHERE \r\n  symbol = '$stock_id';"
    }
   ]
  }
 ]
}